version: '3.6'
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - shared-tmp:/tmp
      - ./docker-entrypoint:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgrespassword
      TZ: Pacific/Honolulu
  backend:
    build: .
    volumes:
      - shared-tmp:/tmp
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
  graphql-engine:
    image: hasura/graphql-engine:v2.25.1
    ports:
      - '8080:8080'
    restart: always
    environment:
      ## postgres database to store Hasura metadata
      HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      PG_DATABASE_URL: postgres://postgres:postgrespassword@postgres:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: 'true'
      HASURA_GRAPHQL_DEV_MODE: 'true'
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
volumes:
  postgres_data:
  docker-entrypoint:
  shared-tmp:
