version: '3.6'
services:
  postgres:
    image: postgres:15
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - shared-tmp:/tmp
      - ./docker-entrypoint:/docker-entrypoint-initdb.d/
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: postgrespassword
      TZ: Pacific/Honolulu
  backend:
    build: .
    volumes:
      - shared-tmp:/tmp
    depends_on:
      - postgres
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres_data:
  docker-entrypoint:
  shared-tmp:
